Repository geokrety/geokrety-website, pull requests merged in 2018-10, with the labels that each got.

#165 Deploy to prod
  website/defektoskop.php
  website/help/bg/help.html
  website/help/cs/help.html
  website/help/it/help.html
  website/help/nl/help.html
  website/lingering.php
  website/recent_newscomments_fn.php
  website/rzeczy/lang/cs_CZ.UTF-8/LC_MESSAGES/messages.mo
  website/rzeczy/lang/cs_CZ.UTF-8/LC_MESSAGES/messages.po
Labels: *PROD*

#173 Fixes #172 windows install
  docker/mariadb/00_database-create-geokrety-db.sql
  docker/mariadb/01_grant-root.sql
  docker/mariadb/10_gk-waypointy-country.sql
  docker/mariadb/11_gk-waypointy-type.sql
Labels: bug

#184 Deploy to prod
  website/aktualizuj.php
  website/majluj.php
Labels: *PROD*

#196 Fixes #193 chain QA test within travis build
  .travis.yml
  .travis_hook_qa.sh
  .travis_wait_build.sh
Labels: enhancement, test-related, travis
