Repository geokrety/geokrety-website, pull requests merged in 2019-01, with the labels that each got.

#236 fixes #235 duplicate credits
  website/__sentry.php
  website/halloffame.php
  website/smarty_start.php
Labels: bug

#241 Deploy to prod
  Makefile
  docker-compose.boly38.yml
  docker-compose.staging.yml
  website/__sentry.php
  website/aktualizuj.php
  website/api-login2secid.php
  website/api-secid-change.php
  website/czy_obserwowany.php
  website/czysc.php
  website/db.php
  website/defektoskop.php
  website/email_errors.php
  website/fn_haslo.php
  website/halloffame.php
  website/help/pl/help.html
  website/konkret-mapka.php
  website/lost_mapka.php
  website/mapka_kretow.php
  website/obrazek.php
  website/obserwuj.php
  website/ostatnie_obrazki_uzytkownika.php
  website/recent_comments_fn.php
  website/recent_moves.php
  website/recent_newscomments_fn.php
  website/register.fn.php
  website/rzeczy/lang/de_DE.UTF-8/LC_MESSAGES/messages.mo
  website/rzeczy/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/fr_FR.UTF-8/LC_MESSAGES/messages.mo
  website/rzeczy/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/messages.po.txt
  website/smarty_start.php
  website/templates/plugins/function.login_check.php
  website/timeline.php
  website/verify_mail.php
  website/whoiskret.php
  website/whoiswho.php
  website/wybierz_jezyk.php
Labels: *PROD*

#245 Fix #243: include_once inside function is bad idea
  website/aktualizuj.php
  website/api-login2secid.php
  website/api-secid-change.php
  website/czy_obserwowany.php
  website/czysc.php
  website/email_errors.php
  website/fn_haslo.php
  website/konkret-mapka.php
  website/lost_mapka.php
  website/mapka_kretow.php
  website/obrazek.php
  website/obserwuj.php
  website/ostatnie_obrazki_uzytkownika.php
  website/recent_comments_fn.php
  website/recent_moves.php
  website/recent_newscomments_fn.php
  website/register.fn.php
  website/templates/plugins/function.login_check.php
  website/timeline.php
  website/verify_mail.php
  website/whoiskret.php
  website/whoiswho.php
  website/wybierz_jezyk.php
Labels: *PROD*

#249 Fix #248: GeoKrety Toolbox fail to retrieve coordinates
  website/download/GeoKrety.Toolbox.user.js
Labels: bug

#247 Feature/gkdb
  .gitignore
  .travis.yml
  docker/mariadb/10_gk-waypointy-country.sql
  docker/mariadb/11_gk-waypointy-type.sql
  gkShell/README.md
  gkShell/config/testdb/.gitignore
  gkShell/config/testdb/__create_prefix
  gkShell/config/testdb/__use_prefix
  gkShell/config/testdb/createTestDb.sh
  gkShell/config/testdb/generateSql.sh
  gkShell/docker-compose.yml
  gkShell/gk.sh
  phpunit.xml
  tests/01_LDHelperTest.php
  tests/02_CreditsTest.php
  tests/03_SocialGroupsTest.php
  tests/D00_GKDBTest.php
  tests/D01_RecentMovesTest.php
  tests/README.md
  tests/bootstrap.php
  tests/config/.gitignore
  tests/config/generateTestConfig.sh
  tests/config/konfig-mysql.php
  tests/lib/GKTestCase.php
  website/defektoskop.php
  website/index.php
  website/konkret-tabelka.php
  website/konkret.php
  website/lib/GKDB.class.php
  website/lib/SpeedTest.php
  website/lib/geokrety/repository/WaypointyRepository.class.php
  website/mygeokrets.php
  website/mypage.php
  website/poprawki.php
  website/recent_moves.php
  website/recentlogs.php
  website/ruchy.php
  website/speedtest.php
  website/szukaj-ajax.php
  website/szukaj.php
  website/templates/konfig-credits.php
  website/templates/konfig.php
  website/waypoint_info.php
Labels: sentry

#252 Deploy to prod
  .gitignore
  .travis.yml
  docker/mariadb/10_gk-waypointy-country.sql
  docker/mariadb/11_gk-waypointy-type.sql
  gkShell/README.md
  gkShell/config/testdb/.gitignore
  gkShell/config/testdb/__create_prefix
  gkShell/config/testdb/__use_prefix
  gkShell/config/testdb/createTestDb.sh
  gkShell/config/testdb/generateSql.sh
  gkShell/docker-compose.yml
  gkShell/gk.sh
  phpunit.xml
  tests/01_LDHelperTest.php
  tests/02_CreditsTest.php
  tests/03_SocialGroupsTest.php
  tests/D00_GKDBTest.php
  tests/D01_RecentMovesTest.php
  tests/README.md
  tests/bootstrap.php
  tests/config/.gitignore
  tests/config/generateTestConfig.sh
  tests/config/konfig-mysql.php
  tests/lib/GKTestCase.php
  website/defektoskop.php
  website/index.php
  website/konkret-tabelka.php
  website/konkret.php
  website/lib/GKDB.class.php
  website/lib/SpeedTest.php
  website/lib/geokrety/repository/WaypointyRepository.class.php
  website/mygeokrets.php
  website/mypage.php
  website/poprawki.php
  website/recent_moves.php
  website/recentlogs.php
  website/ruchy.php
  website/rzeczy/lang/de_DE.UTF-8/LC_MESSAGES/messages.mo
  website/rzeczy/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/pl_PL.UTF-8/LC_MESSAGES/messages.mo
  website/rzeczy/lang/pl_PL.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/messages.po.txt
  website/speedtest.php
  website/szukaj-ajax.php
  website/szukaj.php
  website/templates/konfig-credits.php
  website/templates/konfig.php
  website/waypoint_info.php
Labels: *PROD*
