Repository geokrety/geokrety-website, pull requests merged in 2019-05, with the labels that each got.

#307 Deploy to prod
  gkShell/Dockerfile
  gkShell/gk.sh
  website/gkt/inventory.php
  website/gkt/inventory_v3.php
  website/gkt/search.php
  website/gkt/search_v3.php
  website/gkt2/inventory.php
  website/gkt2/inventory_v3.php
  website/gkt2/search.php
  website/gkt2/search_v3.php
  website/go2geo/go2geo.php
  website/m/qr.php
  website/rzeczy/lang/bg_BG.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/ca_ES.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/cs_CZ.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/da_DK.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/el_GR.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/et_EE.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/fi_FI.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/hu_HU.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/id_ID.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/it_IT.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/lt_LT.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/lv_LV.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/nl_NL.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/no_NO.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/pl_PL.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/ro_RO.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/ru_RU.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/sk_SK.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/sq_AL.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/sv_SE.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/th_TH.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/tl_PH.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/tr_TR.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/uk_UA.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/zh_CN.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/zu_ZA.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/messages.po.txt
  website/templates/labels/index.php
  website/templates/labels/label-2.php
  website/templates/labels/label.php
  website/templates/labels/label2.php
  website/wybierz_jezyk.php
Labels: *PROD*, bug

#311 Quick Fix #309 allow 4 characters as waypointy code
  website/funkcje.js
  website/race_add.js
  website/ruchy.php
  website/szukaj-ajax.php
  website/templates/konfig.php
Labels: bug

#319 Fix #318: enforce usage of parameter in export2.php
  website/export2.php
Labels: bug, cyber security

#320 Deploy to prod
  website/export2.php
  website/longin.php
  website/rzeczy/lang/bg_BG.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/ca_ES.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/cs_CZ.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/da_DK.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/de_DE.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/el_GR.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/es_ES.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/et_EE.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/fi_FI.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/fr_FR.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/hu_HU.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/id_ID.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/it_IT.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/lt_LT.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/lv_LV.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/nl_NL.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/no_NO.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/pl_PL.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/pt_PT.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/ro_RO.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/ru_RU.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/sk_SK.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/sq_AL.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/sv_SE.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/th_TH.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/tl_PH.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/tr_TR.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/uk_UA.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/zh_CN.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/zu_ZA.UTF-8/LC_MESSAGES/messages.po
Labels: *PROD*

#333 Deploy to prod
  website/_zmien_ownera_geokreta.php
  website/edit.php
  website/help/tr/help.html
  website/register.fn.php
  website/rzeczy/lang/nl_NL.UTF-8/LC_MESSAGES/messages.mo
  website/rzeczy/lang/nl_NL.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/ru_RU.UTF-8/LC_MESSAGES/messages.mo
  website/rzeczy/lang/ru_RU.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/lang/tr_TR.UTF-8/LC_MESSAGES/messages.mo
  website/rzeczy/lang/tr_TR.UTF-8/LC_MESSAGES/messages.po
  website/rzeczy/messages.po.txt
  website/templates/konfig.php
Labels: *PROD*
